spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/text2sql
    username: postgres
    password: 1234
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
