spring:
  application:
    name: text2sql

  datasource:
      url: ${SPRING_DATASOURCE_URL}
      username: ${SPRING_DATASOURCE_USERNAME}
      password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
      javax:
        persistence:
          validation:
            mode: none

  sql:
    init:
      mode: always
      platform: postgres
      schema-locations: classpath:schema.sql

# logging ayar?n? istedi?inde açabilirsin:
# logging:
#   level:
#     org.springframework.security: TRACE
#   pattern:
#     console: "%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n"
